INSERT INTO Pregunta VALUES 
(1,"¿En dónde se deben almacenar suministros para una emergencia?","Contingencia"),
(2,"¿Dónde deben estar almacenados los números de teléfono en caso de emergencia?","Contingencia"),
(3,"¿Además de en tu hogar en dónde más puedes refugiarte ante un (Sismo, inundación y tormentas tropicales)?","Contingencia"),
(4,"¿Quiénes deben conocer cómo es el sonido de las sirenas de emergencia?","Contingencia"),
(5,"¿Qué se debe tomar en cuenta para preparar suministros de emergencia?","Contingencia"),
(6,"¿Qué es lo más importante que se debe considerar al seleccionar alimentos para suministro de emergencia?","Contingencia"),
(7,"¿Bajo qué condicion se deben guardar los alimentos?","Contingencia"),
(8,"Además de los factores climáticos, ¿qué otros factores podrían arruinar los alimentos resguardados?","Contingencia"),
(9,"¿Qué utensilios se deben llevar consigo?","Contingencia"),
(10,"¿Qué cantidad de agua se debe llevar por día por cada persona en casos de emergencia?","Contingencia"),
(11,"¿Qué se debe de hacer ante un sismo?","Sismo"),
(12,"¿Qué necesito saber para prevenir emergencias?","Sismo"),
(13,"(Durante el sismo) ¿Qué se debe tomar en cuenta?","Sismo"),
(14,"(Durante el sismo) Las personas más expuestas al riesgo son los adultos con problemas físicos, niños y embarazadas","Sismo"),
(15,"Dado que un sismo dura en promedio 45 segundos, no vale la pena que desalojen pisos superiores, pues cuando lleguen abajo ya acabo el sismo y habrán corrido el riesgo de caerse y lastimarse","Sismo"),
(16,"(Durante el sismo) Si no es posible acceder a la zona de seguridad previamente establecida, puede usar escritorios o mesas para protegerse","Sismo"),
(17,"(Después de el sismo) Debo mantener suspendida la corriente eléctrica, el agua y el gas hasta nuevo aviso","Sismo"),
(18,"(Después de el sismo) Si encuentro a alguien herido debo llevarlo con los miembros de emergencias","Sismo"),
(19,"(Después de el sismo) Si encuentro a alguien atrapado debo intentar liberarlo lo antes posible","Sismo"),
(20,"(Después de el sismo) Hay que evitar tocar las líneas de energía caídas u objetos que se encuentren en contacto con dichos cables","Sismo"),
(21,"(Prevención) Queda prohibido almacenar combustible dentro de inmuebles, ya que contribuyen a la propagación violenta de un incendio","Incendio"),
(22,"(Prevención) No es necesario tener un extintor dentro de la casa siempre y cuando haya uno cerca y accesible","Incendio"),
(23,"(Prevención) No es necesario saber cómo funciona un extintor ya que es muy sencillo su uso","Incendio"),
(24,"(Durante) La persona que descubre el fuego deberá tratar de controlarlo con el uso de extintor y, al mismo tiempo deberá alertar sobre el mismo","Incendio"),
(25,"(Durante) Si el incendio no es de gran magnitud no es necesario dar alarma ni aviso general de éste","Incendio"),
(26,"(Durante) Ante el incendio no es necesario apagar equipos electrónicos","Incendio"),
(27,"(Durante) Los incendios los apagan los bomberos","Incendio"),
(28,"(Después) Para regresar al interior del inmueble es necesario que las personas responsables de Protección Civil den la autorización","Incendio"),
(29,"Sólo se podrá regresar si las condiciones del inmueble son seguras","Incendio"),
(30,"Es importante no suspender la corriente de agua en ningún momento","Incendio");