INSERT INTO pregunta (opcion1,opcion2,opcion3,opcion4) VALUES
("Casa y auto",
"Trabajo y otras bodegas",
"Jardin",
"No sé"),
("Telefono de padres",
"Anotados en el refrigerador",
"Anotados en los telefonos de los niños",
"Todas las anteriores"),
("Casa de vecinos y otros familiares",
"Lugares designados como refugios por las autoridades",
"Centros comerciales",
"No sé"),
("Los jefes de familia",
"Los niños y ancianos",
"Las autoridades competentes ",
"Todos los anteriores"),
("La fecha de caducidad",
"El sabor",
"Que la comida lleve preparaciones complicadas",
"No sé"),
("Que sepan bien",
"Que duren mucho tiempo",
"Que satisfagan las necesidades nutrimentales",
"No sé"),
("Bajo el sol",
"En un lugar fresco",
"Alejados de fuentes de calor",
"No sé"),
("Roedores y otros animales",
"Aire",
"Niños y adultos curiosos",
"No sé"),
("Cuchillos, cubiertos, vasos y toallas de papel",
"Manteles , servilletas, vajilla",
"Mesas donde comer, portavasos",
"No sé"),
("Un galon por persona, menos si se vive en zonas calidas",
"Un litro por persona, mas si se vive en zonas frias",
"Un galon por persona, mas si se vive en zonas calidas",
"Dos litros por persona, mas si se vive en zonas frias"),
("Tomar pertenencias importantes",
"Resguardar pertenencias",
"Desalojar",
"No sé"),
("Informarme sobre el plan de emergencia",
"Instrucciones sobre los procedimientos de evacuación",
"Conocer las señalizaciones pertinentes",
"Todas las anteriores"),
("Guardar siempre la calma, no corro, no grito, no empujo",
"Verificar que los objetos materiales esten a salvo y bien asegurados",
"Buscar los ascensores más cercanos para evacuar de la forma más veloz posible",
"Desconectar gas, luz y agua antes de desalojar"),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL),
("Verdadero",
"Falso",NULL,NULL);